# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'analyse.ui'
#
# Created: Tue May 17 22:46:14 2016
#      by: PyQt4 UI code generator 4.11
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(919, 678)
        MainWindow.setMaximumSize(QtCore.QSize(1000, 16777215))
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.StartButton = QtGui.QPushButton(self.centralwidget)
        self.StartButton.setGeometry(QtCore.QRect(150, 560, 75, 23))
        self.StartButton.setObjectName(_fromUtf8("StartButton"))
        self.SubjectText = QtGui.QLineEdit(self.centralwidget)
        self.SubjectText.setGeometry(QtCore.QRect(296, 9, 133, 20))
        self.SubjectText.setObjectName(_fromUtf8("SubjectText"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(209, 9, 81, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(610, 10, 24, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.DayCombo = QtGui.QComboBox(self.centralwidget)
        self.DayCombo.setGeometry(QtCore.QRect(485, 10, 69, 20))
        self.DayCombo.setObjectName(_fromUtf8("DayCombo"))
        self.DayCombo.addItem(_fromUtf8(""))
        self.DayCombo.addItem(_fromUtf8(""))
        self.DayCombo.addItem(_fromUtf8(""))
        self.DayCombo.addItem(_fromUtf8(""))
        self.DayCombo.addItem(_fromUtf8(""))
        self.DayCombo.addItem(_fromUtf8(""))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(460, 10, 19, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.BlockCombo = QtGui.QComboBox(self.centralwidget)
        self.BlockCombo.setGeometry(QtCore.QRect(640, 10, 69, 20))
        self.BlockCombo.setObjectName(_fromUtf8("BlockCombo"))
        self.BlockCombo.addItem(_fromUtf8(""))
        self.BlockCombo.addItem(_fromUtf8(""))
        self.BlockCombo.addItem(_fromUtf8(""))
        self.BlockCombo.addItem(_fromUtf8(""))
        self.BlockCombo.addItem(_fromUtf8(""))
        self.graphWindow = QtGui.QWidget(self.centralwidget)
        self.graphWindow.setGeometry(QtCore.QRect(9, 63, 691, 491))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphWindow.sizePolicy().hasHeightForWidth())
        self.graphWindow.setSizePolicy(sizePolicy)
        self.graphWindow.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.graphWindow.setObjectName(_fromUtf8("graphWindow"))
        self.mplvl = QtGui.QVBoxLayout(self.graphWindow)
        self.mplvl.setMargin(0)
        self.mplvl.setObjectName(_fromUtf8("mplvl"))
        self.NextButton = QtGui.QPushButton(self.centralwidget)
        self.NextButton.setGeometry(QtCore.QRect(260, 560, 75, 23))
        self.NextButton.setObjectName(_fromUtf8("NextButton"))
        self.DeleteButton = QtGui.QPushButton(self.centralwidget)
        self.DeleteButton.setGeometry(QtCore.QRect(360, 560, 111, 23))
        self.DeleteButton.setObjectName(_fromUtf8("DeleteButton"))
        self.QuitButton = QtGui.QPushButton(self.centralwidget)
        self.QuitButton.setGeometry(QtCore.QRect(641, 560, 75, 23))
        self.QuitButton.setObjectName(_fromUtf8("QuitButton"))
        self.FromLabel = QtGui.QLabel(self.centralwidget)
        self.FromLabel.setGeometry(QtCore.QRect(270, 40, 46, 13))
        self.FromLabel.setText(_fromUtf8(""))
        self.FromLabel.setObjectName(_fromUtf8("FromLabel"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(400, 40, 46, 13))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.ToLabel = QtGui.QLabel(self.centralwidget)
        self.ToLabel.setGeometry(QtCore.QRect(510, 40, 46, 13))
        self.ToLabel.setText(_fromUtf8(""))
        self.ToLabel.setObjectName(_fromUtf8("ToLabel"))
        self.Reaction_Time = QtGui.QLabel(self.centralwidget)
        self.Reaction_Time.setGeometry(QtCore.QRect(710, 100, 201, 20))
        self.Reaction_Time.setObjectName(_fromUtf8("Reaction_Time"))
        self.Movement_Time = QtGui.QLabel(self.centralwidget)
        self.Movement_Time.setGeometry(QtCore.QRect(710, 130, 191, 16))
        self.Movement_Time.setObjectName(_fromUtf8("Movement_Time"))
        self.Response_Time = QtGui.QLabel(self.centralwidget)
        self.Response_Time.setGeometry(QtCore.QRect(710, 160, 191, 16))
        self.Response_Time.setObjectName(_fromUtf8("Response_Time"))
        self.Max_Velocity = QtGui.QLabel(self.centralwidget)
        self.Max_Velocity.setGeometry(QtCore.QRect(710, 190, 191, 16))
        self.Max_Velocity.setObjectName(_fromUtf8("Max_Velocity"))
        self.Max_Acc = QtGui.QLabel(self.centralwidget)
        self.Max_Acc.setGeometry(QtCore.QRect(710, 220, 191, 16))
        self.Max_Acc.setObjectName(_fromUtf8("Max_Acc"))
        self.Deviation = QtGui.QLabel(self.centralwidget)
        self.Deviation.setGeometry(QtCore.QRect(710, 250, 191, 16))
        self.Deviation.setObjectName(_fromUtf8("Deviation"))
        self.Actual_Dist = QtGui.QLabel(self.centralwidget)
        self.Actual_Dist.setGeometry(QtCore.QRect(710, 310, 191, 16))
        self.Actual_Dist.setObjectName(_fromUtf8("Actual_Dist"))
        self.Real_Dist = QtGui.QLabel(self.centralwidget)
        self.Real_Dist.setGeometry(QtCore.QRect(710, 280, 191, 16))
        self.Real_Dist.setObjectName(_fromUtf8("Real_Dist"))
        self.Dist_Per = QtGui.QLabel(self.centralwidget)
        self.Dist_Per.setGeometry(QtCore.QRect(710, 340, 191, 16))
        self.Dist_Per.setObjectName(_fromUtf8("Dist_Per"))
        self.GenerateButton = QtGui.QPushButton(self.centralwidget)
        self.GenerateButton.setGeometry(QtCore.QRect(500, 560, 111, 23))
        self.GenerateButton.setObjectName(_fromUtf8("GenerateButton"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 919, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.StartButton.setText(_translate("MainWindow", "Start", None))
        self.SubjectText.setText(_translate("MainWindow", "1", None))
        self.label.setText(_translate("MainWindow", "Subject Number", None))
        self.label_2.setText(_translate("MainWindow", "Block", None))
        self.DayCombo.setItemText(0, _translate("MainWindow", "Day 1", None))
        self.DayCombo.setItemText(1, _translate("MainWindow", "Day 2", None))
        self.DayCombo.setItemText(2, _translate("MainWindow", "Day 3", None))
        self.DayCombo.setItemText(3, _translate("MainWindow", "Day 4", None))
        self.DayCombo.setItemText(4, _translate("MainWindow", "Day 5", None))
        self.DayCombo.setItemText(5, _translate("MainWindow", "Performance", None))
        self.label_3.setText(_translate("MainWindow", "Day", None))
        self.BlockCombo.setItemText(0, _translate("MainWindow", "1", None))
        self.BlockCombo.setItemText(1, _translate("MainWindow", "2", None))
        self.BlockCombo.setItemText(2, _translate("MainWindow", "3", None))
        self.BlockCombo.setItemText(3, _translate("MainWindow", "4", None))
        self.BlockCombo.setItemText(4, _translate("MainWindow", "5", None))
        self.NextButton.setText(_translate("MainWindow", "Next", None))
        self.DeleteButton.setText(_translate("MainWindow", "Delete Record", None))
        self.QuitButton.setText(_translate("MainWindow", "Quit", None))
        self.label_5.setText(_translate("MainWindow", "TO", None))
        self.Reaction_Time.setText(_translate("MainWindow", "Reaction Time", None))
        self.Movement_Time.setText(_translate("MainWindow", "Movement Time", None))
        self.Response_Time.setText(_translate("MainWindow", "Response Time", None))
        self.Max_Velocity.setText(_translate("MainWindow", "Max Velocity", None))
        self.Max_Acc.setText(_translate("MainWindow", "Max Acc", None))
        self.Deviation.setText(_translate("MainWindow", "End Point Deviation", None))
        self.Actual_Dist.setText(_translate("MainWindow", "Actual Distance Traversed", None))
        self.Real_Dist.setText(_translate("MainWindow", "Real Distance", None))
        self.Dist_Per.setText(_translate("MainWindow", "Distance Percent Deviation", None))
        self.GenerateButton.setText(_translate("MainWindow", "Generate Record File", None))

