# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'database_entry.ui'
#
# Created: Thu May 19 11:54:47 2016
#      by: PyQt4 UI code generator 4.11
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(837, 611)
        font = QtGui.QFont()
        font.setPointSize(11)
        MainWindow.setFont(font)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.SubjectNo = QtGui.QLabel(self.centralwidget)
        self.SubjectNo.setGeometry(QtCore.QRect(25, 141, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.SubjectNo.setFont(font)
        self.SubjectNo.setObjectName(_fromUtf8("SubjectNo"))
        self.text_subNum = QtGui.QLineEdit(self.centralwidget)
        self.text_subNum.setGeometry(QtCore.QRect(152, 141, 121, 24))
        self.text_subNum.setObjectName(_fromUtf8("text_subNum"))
        self.SubjectName = QtGui.QLabel(self.centralwidget)
        self.SubjectName.setGeometry(QtCore.QRect(312, 141, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.SubjectName.setFont(font)
        self.SubjectName.setObjectName(_fromUtf8("SubjectName"))
        self.label_age = QtGui.QLabel(self.centralwidget)
        self.label_age.setGeometry(QtCore.QRect(40, 200, 91, 24))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_age.setFont(font)
        self.label_age.setObjectName(_fromUtf8("label_age"))
        self.label_lang = QtGui.QLabel(self.centralwidget)
        self.label_lang.setGeometry(QtCore.QRect(40, 270, 101, 21))
        self.label_lang.setObjectName(_fromUtf8("label_lang"))
        self.combo_gender = QtGui.QComboBox(self.centralwidget)
        self.combo_gender.setGeometry(QtCore.QRect(383, 200, 83, 24))
        self.combo_gender.setObjectName(_fromUtf8("combo_gender"))
        self.combo_gender.addItem(_fromUtf8(""))
        self.combo_gender.addItem(_fromUtf8(""))
        self.label_gender = QtGui.QLabel(self.centralwidget)
        self.label_gender.setGeometry(QtCore.QRect(330, 200, 47, 24))
        self.label_gender.setObjectName(_fromUtf8("label_gender"))
        self.text_lang = QtGui.QLineEdit(self.centralwidget)
        self.text_lang.setGeometry(QtCore.QRect(150, 270, 131, 20))
        self.text_lang.setObjectName(_fromUtf8("text_lang"))
        self.label_hand = QtGui.QLabel(self.centralwidget)
        self.label_hand.setGeometry(QtCore.QRect(330, 270, 121, 21))
        self.label_hand.setObjectName(_fromUtf8("label_hand"))
        self.combo_hand = QtGui.QComboBox(self.centralwidget)
        self.combo_hand.setGeometry(QtCore.QRect(470, 270, 71, 21))
        self.combo_hand.setObjectName(_fromUtf8("combo_hand"))
        self.combo_hand.addItem(_fromUtf8(""))
        self.combo_hand.addItem(_fromUtf8(""))
        self.text_age = QtGui.QLineEdit(self.centralwidget)
        self.text_age.setGeometry(QtCore.QRect(90, 200, 167, 24))
        self.text_age.setObjectName(_fromUtf8("text_age"))
        self.label_occupation = QtGui.QLabel(self.centralwidget)
        self.label_occupation.setGeometry(QtCore.QRect(40, 340, 91, 21))
        self.label_occupation.setObjectName(_fromUtf8("label_occupation"))
        self.text_occupation = QtGui.QLineEdit(self.centralwidget)
        self.text_occupation.setGeometry(QtCore.QRect(140, 340, 261, 20))
        self.text_occupation.setObjectName(_fromUtf8("text_occupation"))
        self.label_leisure = QtGui.QLabel(self.centralwidget)
        self.label_leisure.setGeometry(QtCore.QRect(40, 400, 201, 24))
        self.label_leisure.setObjectName(_fromUtf8("label_leisure"))
        self.combo_leisure = QtGui.QComboBox(self.centralwidget)
        self.combo_leisure.setGeometry(QtCore.QRect(250, 400, 161, 24))
        self.combo_leisure.setObjectName(_fromUtf8("combo_leisure"))
        self.combo_leisure.addItem(_fromUtf8(""))
        self.combo_leisure.addItem(_fromUtf8(""))
        self.combo_leisure.addItem(_fromUtf8(""))
        self.combo_leisure.addItem(_fromUtf8(""))
        self.combo_leisure.addItem(_fromUtf8(""))
        self.label_week = QtGui.QLabel(self.centralwidget)
        self.label_week.setGeometry(QtCore.QRect(41, 461, 51, 18))
        self.label_week.setObjectName(_fromUtf8("label_week"))
        self.text_week = QtGui.QLineEdit(self.centralwidget)
        self.text_week.setGeometry(QtCore.QRect(100, 461, 167, 24))
        self.text_week.setObjectName(_fromUtf8("text_week"))
        self.label_time = QtGui.QLabel(self.centralwidget)
        self.label_time.setGeometry(QtCore.QRect(340, 460, 101, 16))
        self.label_time.setObjectName(_fromUtf8("label_time"))
        self.combo_time = QtGui.QComboBox(self.centralwidget)
        self.combo_time.setGeometry(QtCore.QRect(450, 460, 121, 22))
        self.combo_time.setObjectName(_fromUtf8("combo_time"))
        self.combo_time.addItem(_fromUtf8(""))
        self.combo_time.addItem(_fromUtf8(""))
        self.combo_time.addItem(_fromUtf8(""))
        self.button_submit = QtGui.QPushButton(self.centralwidget)
        self.button_submit.setGeometry(QtCore.QRect(160, 530, 75, 23))
        self.button_submit.setObjectName(_fromUtf8("button_submit"))
        self.button_clear = QtGui.QPushButton(self.centralwidget)
        self.button_clear.setGeometry(QtCore.QRect(340, 530, 75, 23))
        self.button_clear.setObjectName(_fromUtf8("button_clear"))
        self.button_quit = QtGui.QPushButton(self.centralwidget)
        self.button_quit.setGeometry(QtCore.QRect(500, 530, 75, 23))
        self.button_quit.setObjectName(_fromUtf8("button_quit"))
        self.logo1 = QtGui.QLabel(self.centralwidget)
        self.logo1.setGeometry(QtCore.QRect(40, 10, 181, 91))
        self.logo1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.logo1.setText(_fromUtf8(""))
        self.logo1.setPixmap(QtGui.QPixmap(_fromUtf8("13552-REPAR-COUL.png")))
        self.logo1.setObjectName(_fromUtf8("logo1"))
        self.logo2 = QtGui.QLabel(self.centralwidget)
        self.logo2.setGeometry(QtCore.QRect(590, 10, 231, 91))
        self.logo2.setText(_fromUtf8(""))
        self.logo2.setPixmap(QtGui.QPixmap(_fromUtf8("medicine_logo_horiz_eng_outlined_750.png")))
        self.logo2.setObjectName(_fromUtf8("logo2"))
        self.text_subjectName = QtGui.QLineEdit(self.centralwidget)
        self.text_subjectName.setGeometry(QtCore.QRect(429, 141, 401, 24))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.text_subjectName.setFont(font)
        self.text_subjectName.setObjectName(_fromUtf8("text_subjectName"))
        self.label_TDCS = QtGui.QLabel(self.centralwidget)
        self.label_TDCS.setGeometry(QtCore.QRect(480, 340, 101, 16))
        self.label_TDCS.setObjectName(_fromUtf8("label_TDCS"))
        self.text_TDCS = QtGui.QLineEdit(self.centralwidget)
        self.text_TDCS.setGeometry(QtCore.QRect(610, 340, 113, 20))
        self.text_TDCS.setObjectName(_fromUtf8("text_TDCS"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 837, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Database Entry", None))
        self.SubjectNo.setText(_translate("MainWindow", "Subject Number*", None))
        self.text_subNum.setText(_translate("MainWindow", "1", None))
        self.SubjectName.setText(_translate("MainWindow", "Subject Name*", None))
        self.label_age.setText(_translate("MainWindow", "Age", None))
        self.label_lang.setText(_translate("MainWindow", "Native Tongue", None))
        self.combo_gender.setItemText(0, _translate("MainWindow", "Male", None))
        self.combo_gender.setItemText(1, _translate("MainWindow", "Female", None))
        self.label_gender.setText(_translate("MainWindow", "Gender", None))
        self.text_lang.setText(_translate("MainWindow", "English", None))
        self.label_hand.setText(_translate("MainWindow", "Dominant Hand", None))
        self.combo_hand.setItemText(0, _translate("MainWindow", "Right", None))
        self.combo_hand.setItemText(1, _translate("MainWindow", "Left", None))
        self.text_age.setText(_translate("MainWindow", "20", None))
        self.label_occupation.setText(_translate("MainWindow", "Occupation", None))
        self.text_occupation.setText(_translate("MainWindow", "Student", None))
        self.label_leisure.setText(_translate("MainWindow", "Frequency of Leisure Activity ", None))
        self.combo_leisure.setItemText(0, _translate("MainWindow", "Almost Every Day", None))
        self.combo_leisure.setItemText(1, _translate("MainWindow", "5 times per week", None))
        self.combo_leisure.setItemText(2, _translate("MainWindow", "2-3 times per week", None))
        self.combo_leisure.setItemText(3, _translate("MainWindow", "Once per week", None))
        self.combo_leisure.setItemText(4, _translate("MainWindow", "<1 per week", None))
        self.label_week.setText(_translate("MainWindow", "Week*", None))
        self.text_week.setText(_translate("MainWindow", "1", None))
        self.label_time.setText(_translate("MainWindow", "Time of Day", None))
        self.combo_time.setItemText(0, _translate("MainWindow", "9 to 11", None))
        self.combo_time.setItemText(1, _translate("MainWindow", "11 to 13", None))
        self.combo_time.setItemText(2, _translate("MainWindow", "13 to 15", None))
        self.button_submit.setText(_translate("MainWindow", "Submit", None))
        self.button_clear.setText(_translate("MainWindow", "Clear", None))
        self.button_quit.setText(_translate("MainWindow", "Quit", None))
        self.text_subjectName.setText(_translate("MainWindow", "abc", None))
        self.label_TDCS.setText(_translate("MainWindow", "TDCS Number*", None))
        self.text_TDCS.setText(_translate("MainWindow", "1", None))

