# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plotter.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1924, 1063)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.label_subNo = QtGui.QLabel(self.centralwidget)
        self.label_subNo.setGeometry(QtCore.QRect(380, 60, 101, 16))
        self.label_subNo.setObjectName(_fromUtf8("label_subNo"))
        self.text_subNo = QtGui.QLineEdit(self.centralwidget)
        self.text_subNo.setGeometry(QtCore.QRect(480, 60, 113, 20))
        self.text_subNo.setObjectName(_fromUtf8("text_subNo"))
        self.label_filter = QtGui.QLabel(self.centralwidget)
        self.label_filter.setGeometry(QtCore.QRect(610, 60, 81, 16))
        self.label_filter.setObjectName(_fromUtf8("label_filter"))
        self.combo_filter = QtGui.QComboBox(self.centralwidget)
        self.combo_filter.setGeometry(QtCore.QRect(710, 60, 69, 22))
        self.combo_filter.setObjectName(_fromUtf8("combo_filter"))
        self.combo_filter.addItem(_fromUtf8(""))
        self.combo_filter.addItem(_fromUtf8(""))
        self.label_param = QtGui.QLabel(self.centralwidget)
        self.label_param.setGeometry(QtCore.QRect(430, 90, 81, 21))
        self.label_param.setObjectName(_fromUtf8("label_param"))
        self.combo_param = QtGui.QComboBox(self.centralwidget)
        self.combo_param.setGeometry(QtCore.QRect(530, 90, 221, 22))
        self.combo_param.setObjectName(_fromUtf8("combo_param"))
        self.combo_param.addItem(_fromUtf8(""))
        self.combo_param.addItem(_fromUtf8(""))
        self.combo_param.addItem(_fromUtf8(""))
        self.combo_param.addItem(_fromUtf8(""))
        self.combo_param.addItem(_fromUtf8(""))
        self.combo_param.addItem(_fromUtf8(""))
        self.combo_param.addItem(_fromUtf8(""))
        self.combo_param.addItem(_fromUtf8(""))
        self.combo_param.addItem(_fromUtf8(""))
        self.combo_param.addItem(_fromUtf8(""))
        self.combo_param.addItem(_fromUtf8(""))
        self.combo_param.addItem(_fromUtf8(""))
        self.combo_param.addItem(_fromUtf8(""))
        self.combo_param.addItem(_fromUtf8(""))
        self.combo_param.addItem(_fromUtf8(""))
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 140, 1471, 801))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.mplvl = QtGui.QVBoxLayout(self.widget)
        self.mplvl.setObjectName(_fromUtf8("mplvl"))
        self.PlotButton = QtGui.QPushButton(self.centralwidget)
        self.PlotButton.setGeometry(QtCore.QRect(350, 960, 75, 23))
        self.PlotButton.setObjectName(_fromUtf8("PlotButton"))
        self.ClearButton = QtGui.QPushButton(self.centralwidget)
        self.ClearButton.setGeometry(QtCore.QRect(500, 960, 75, 23))
        self.ClearButton.setObjectName(_fromUtf8("ClearButton"))
        self.QuitButton = QtGui.QPushButton(self.centralwidget)
        self.QuitButton.setGeometry(QtCore.QRect(830, 960, 75, 23))
        self.QuitButton.setObjectName(_fromUtf8("QuitButton"))
        self.logo1 = QtGui.QLabel(self.centralwidget)
        self.logo1.setGeometry(QtCore.QRect(20, 10, 141, 71))
        self.logo1.setText(_fromUtf8(""))
        self.logo1.setPixmap(QtGui.QPixmap(_fromUtf8("13552-REPAR-COUL.png")))
        self.logo1.setObjectName(_fromUtf8("logo1"))
        self.logo2 = QtGui.QLabel(self.centralwidget)
        self.logo2.setGeometry(QtCore.QRect(1660, 10, 231, 51))
        self.logo2.setText(_fromUtf8(""))
        self.logo2.setPixmap(QtGui.QPixmap(_fromUtf8("medicine_logo_horiz_eng_outlined_750.png")))
        self.logo2.setObjectName(_fromUtf8("logo2"))
        self.SaveButton = QtGui.QPushButton(self.centralwidget)
        self.SaveButton.setGeometry(QtCore.QRect(660, 960, 75, 23))
        self.SaveButton.setObjectName(_fromUtf8("SaveButton"))
        self.ImprovementLabel = QtGui.QLabel(self.centralwidget)
        self.ImprovementLabel.setGeometry(QtCore.QRect(1540, 130, 371, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS PMincho"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ImprovementLabel.setFont(font)
        self.ImprovementLabel.setObjectName(_fromUtf8("ImprovementLabel"))
        self.rep_info = QtGui.QLabel(self.centralwidget)
        self.rep_info.setGeometry(QtCore.QRect(1620, 200, 121, 21))
        self.rep_info.setObjectName(_fromUtf8("rep_info"))
        self.ran_info = QtGui.QLabel(self.centralwidget)
        self.ran_info.setGeometry(QtCore.QRect(1790, 200, 121, 21))
        self.ran_info.setObjectName(_fromUtf8("ran_info"))
        self.d1 = QtGui.QLabel(self.centralwidget)
        self.d1.setGeometry(QtCore.QRect(1510, 240, 46, 13))
        self.d1.setObjectName(_fromUtf8("d1"))
        self.d2 = QtGui.QLabel(self.centralwidget)
        self.d2.setGeometry(QtCore.QRect(1510, 280, 46, 13))
        self.d2.setObjectName(_fromUtf8("d2"))
        self.d1_3 = QtGui.QLabel(self.centralwidget)
        self.d1_3.setGeometry(QtCore.QRect(1510, 320, 46, 13))
        self.d1_3.setObjectName(_fromUtf8("d1_3"))
        self.d1_4 = QtGui.QLabel(self.centralwidget)
        self.d1_4.setGeometry(QtCore.QRect(1510, 360, 46, 13))
        self.d1_4.setObjectName(_fromUtf8("d1_4"))
        self.d1_5 = QtGui.QLabel(self.centralwidget)
        self.d1_5.setGeometry(QtCore.QRect(1510, 400, 46, 13))
        self.d1_5.setObjectName(_fromUtf8("d1_5"))
        self.d1_6 = QtGui.QLabel(self.centralwidget)
        self.d1_6.setGeometry(QtCore.QRect(1510, 440, 81, 16))
        self.d1_6.setObjectName(_fromUtf8("d1_6"))
        self.rep_d1 = QtGui.QLabel(self.centralwidget)
        self.rep_d1.setGeometry(QtCore.QRect(1640, 240, 46, 13))
        self.rep_d1.setText(_fromUtf8(""))
        self.rep_d1.setObjectName(_fromUtf8("rep_d1"))
        self.ran_d1 = QtGui.QLabel(self.centralwidget)
        self.ran_d1.setGeometry(QtCore.QRect(1810, 240, 46, 13))
        self.ran_d1.setText(_fromUtf8(""))
        self.ran_d1.setObjectName(_fromUtf8("ran_d1"))
        self.rep_d2 = QtGui.QLabel(self.centralwidget)
        self.rep_d2.setGeometry(QtCore.QRect(1640, 280, 46, 13))
        self.rep_d2.setText(_fromUtf8(""))
        self.rep_d2.setObjectName(_fromUtf8("rep_d2"))
        self.ran_d2 = QtGui.QLabel(self.centralwidget)
        self.ran_d2.setGeometry(QtCore.QRect(1810, 280, 46, 13))
        self.ran_d2.setText(_fromUtf8(""))
        self.ran_d2.setObjectName(_fromUtf8("ran_d2"))
        self.ran_d3 = QtGui.QLabel(self.centralwidget)
        self.ran_d3.setGeometry(QtCore.QRect(1810, 320, 46, 13))
        self.ran_d3.setText(_fromUtf8(""))
        self.ran_d3.setObjectName(_fromUtf8("ran_d3"))
        self.rep_d3 = QtGui.QLabel(self.centralwidget)
        self.rep_d3.setGeometry(QtCore.QRect(1640, 320, 46, 13))
        self.rep_d3.setText(_fromUtf8(""))
        self.rep_d3.setObjectName(_fromUtf8("rep_d3"))
        self.ran_d4 = QtGui.QLabel(self.centralwidget)
        self.ran_d4.setGeometry(QtCore.QRect(1810, 360, 46, 13))
        self.ran_d4.setText(_fromUtf8(""))
        self.ran_d4.setObjectName(_fromUtf8("ran_d4"))
        self.rep_d4 = QtGui.QLabel(self.centralwidget)
        self.rep_d4.setGeometry(QtCore.QRect(1640, 360, 46, 13))
        self.rep_d4.setText(_fromUtf8(""))
        self.rep_d4.setObjectName(_fromUtf8("rep_d4"))
        self.ran_d5 = QtGui.QLabel(self.centralwidget)
        self.ran_d5.setGeometry(QtCore.QRect(1810, 400, 46, 13))
        self.ran_d5.setText(_fromUtf8(""))
        self.ran_d5.setObjectName(_fromUtf8("ran_d5"))
        self.rep_d5 = QtGui.QLabel(self.centralwidget)
        self.rep_d5.setGeometry(QtCore.QRect(1640, 400, 46, 13))
        self.rep_d5.setText(_fromUtf8(""))
        self.rep_d5.setObjectName(_fromUtf8("rep_d5"))
        self.ran_p = QtGui.QLabel(self.centralwidget)
        self.ran_p.setGeometry(QtCore.QRect(1810, 440, 46, 13))
        self.ran_p.setText(_fromUtf8(""))
        self.ran_p.setObjectName(_fromUtf8("ran_p"))
        self.rep_p = QtGui.QLabel(self.centralwidget)
        self.rep_p.setGeometry(QtCore.QRect(1640, 440, 46, 13))
        self.rep_p.setText(_fromUtf8(""))
        self.rep_p.setObjectName(_fromUtf8("rep_p"))
        self.sub_info = QtGui.QLabel(self.centralwidget)
        self.sub_info.setGeometry(QtCore.QRect(1640, 160, 161, 16))
        self.sub_info.setObjectName(_fromUtf8("sub_info"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1924, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Plot Generator", None))
        self.label_subNo.setText(_translate("MainWindow", "Subject Number", None))
        self.text_subNo.setText(_translate("MainWindow", "3", None))
        self.label_filter.setText(_translate("MainWindow", "Filtered Data", None))
        self.combo_filter.setItemText(0, _translate("MainWindow", "Yes", None))
        self.combo_filter.setItemText(1, _translate("MainWindow", "No", None))
        self.label_param.setText(_translate("MainWindow", "Parameter", None))
        self.combo_param.setItemText(0, _translate("MainWindow", "Index Value", None))
        self.combo_param.setItemText(1, _translate("MainWindow", "mean Reaction Time", None))
        self.combo_param.setItemText(2, _translate("MainWindow", "mean Movement Time", None))
        self.combo_param.setItemText(3, _translate("MainWindow", "mean Response Time", None))
        self.combo_param.setItemText(4, _translate("MainWindow", "mean Max Velocity", None))
        self.combo_param.setItemText(5, _translate("MainWindow", "mean Max Acceleration", None))
        self.combo_param.setItemText(6, _translate("MainWindow", "mean End Point Deviation", None))
        self.combo_param.setItemText(7, _translate("MainWindow", "mean Real Distance", None))
        self.combo_param.setItemText(8, _translate("MainWindow", "mean Distance Travelled", None))
        self.combo_param.setItemText(9, _translate("MainWindow", "mean Percentage Deviation", None))
        self.combo_param.setItemText(10, _translate("MainWindow", "overall Max Reaction Time", None))
        self.combo_param.setItemText(11, _translate("MainWindow", "overall Max Movement Time", None))
        self.combo_param.setItemText(12, _translate("MainWindow", "overall Max End Point Deviation", None))
        self.combo_param.setItemText(13, _translate("MainWindow", "overall Max Speed", None))
        self.combo_param.setItemText(14, _translate("MainWindow", "overall Max Acceleration", None))
        self.PlotButton.setText(_translate("MainWindow", "Plot", None))
        self.ClearButton.setText(_translate("MainWindow", "Clear", None))
        self.QuitButton.setText(_translate("MainWindow", "Quit", None))
        self.SaveButton.setText(_translate("MainWindow", "Save Plot", None))
        self.ImprovementLabel.setText(_translate("MainWindow", "Improvement in parameter from baseline in %", None))
        self.rep_info.setText(_translate("MainWindow", "Repeated Sequence", None))
        self.ran_info.setText(_translate("MainWindow", "Random Sequence", None))
        self.d1.setText(_translate("MainWindow", "Day 1", None))
        self.d2.setText(_translate("MainWindow", "Day 2", None))
        self.d1_3.setText(_translate("MainWindow", "Day 3", None))
        self.d1_4.setText(_translate("MainWindow", "Day 4", None))
        self.d1_5.setText(_translate("MainWindow", "Day 5", None))
        self.d1_6.setText(_translate("MainWindow", "Performance", None))
        self.sub_info.setText(_translate("MainWindow", "(Subject Number)", None))

